defaults:
  - base

model_path: Qwen/Qwen3-0.6B
tokenizer_path: Qwen/Qwen2.5-0.5B-Instruct

actor_rollout_ref:
  model:
    use_liger: True
  tokenizer:
    path: ${tokenizer_path}
  actor:
    fsdp_config:
      model_dtype: bfloat16
  ref:
    fsdp_config:
      model_dtype: bfloat16
  rollout:
    max_model_len: 16384
    response_length: 2048
    gpu_memory_utilization: 0.3
    max_num_batched_tokens: 16384
    enforce_eager: False
    free_cache_engine: False

critic:
  model:
    fsdp_config:
      model_dtype: bfloat16

trainer:
  experiment_name: frozenlake-main
  rollout_data_dir: null
  generations_to_log_to_wandb:
    val: 32

es_manager:
  train:
    env_configs:
      tags: ["FrozenLake"]
  val:
    env_configs:
      tags: ["FrozenLake"]

custom_envs:
  FrozenLake:
    max_tokens: 2048
