defaults:
  - base

model_path: Qwen/Qwen3-0.6B

actor_rollout_ref:
  model:
    use_liger: True
  actor:
    fsdp_config:
      model_dtype: bfloat16
  ref:
    fsdp_config:
      model_dtype: bfloat16
  rollout:
    max_model_len: 16384
    response_length: 2048
    max_num_batched_tokens: 16384
    enforce_eager: False
    free_cache_engine: False

critic:
  model:
    fsdp_config:
      model_dtype: bfloat16

trainer:
  experiment_name: frozenlake-main
  rollout_data_dir: null

es_manager:
  train:
    env_configs:
      tags: ["FrozenLake"]
  val:
    env_configs:
      tags: ["FrozenLake"]

custom_envs:
  FrozenLake:
    env_instruction: "You are solving the FrozenLake puzzle. Forbid the whole and go to the target. You may move to the unintended direction due to the slippery ice. Example answer format:\n<think>\nTo forbid the hole and go to the target, I should go left then go up.\n</think>\n\n<answer>\nLeft || Up\n</answer>"
    max_tokens: 2048
