defaults:
  - qwen3_base

actor_rollout_ref:
  actor:
    clip_ratio_high: 0.2
    loss_agg_mode: seq-mean-token-sum-norm

  rollout:
    rollout_filter_ratio: 1.0

trainer:
  experiment_name: frozenlake-dr-ppo
