defaults:
  - qwen3_base

grpo_advantage_length_weight: True

actor_rollout_ref:
  actor:
    use_kl_loss: True
    kl_loss_coef: 0.001
    clip_ratio_high: 0.2

  rollout:
    rollout_filter_ratio: 1.0

algorithm:
  adv_estimator: grpo

trainer:
  experiment_name: frozenlake-grpo

agent_proxy:
  reward_normalization:
    method: mean_std
