defaults:
  - qwen3_base

actor_rollout_ref:
  actor:
    clip_ratio_high: 0.2

  rollout:
    rollout_filter_ratio: 1.0

algorithm:
  kl_ctrl:
    kl_coef: 0.001

trainer:
  project_name: ragen-qwen3
  experiment_name: frozenlake-ppo
